import {
  Activity,
  Airplay,
  AlarmClock,
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Bell,
  Book,
  Bookmark,
  Briefcase,
  Calendar,
  Camera,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  Clock,
  Cloud,
  Code,
  Code2,
  Command,
  Compass,
  Copy,
  CreditCard,
  Crown,
  Database,
  Download,
  Edit,
  ExternalLink,
  Eye,
  File,
  Flag,
  Folder,
  Gift,
  Globe,
  Heart,
  Home,
  Image,
  Inbox,
  Key,
  LayoutGrid,
  Link,
  Lock,
  Mail,
  MapPin,
  MessageCircle,
  Mic,
  Moon,
  Music,
  Palette,
  Paperclip,
  Pin,
  Play,
  Plus,
  Search,
  Send,
  Settings,
  Shield,
  ShoppingCart,
  Smartphone,
  Speaker,
  Star,
  StickyNote,
  Sun,
  Tag,
  Terminal,
  Trash2,
  Upload,
  User,
  Users,
  Video,
  Wand2,
  Wifi,
  Zap,
} from "lucide-react";

import type { IconOption } from "./IconPopover";

export const iconOptions: IconOption[] = [
  {
    id: "file",
    label: "File",
    icon: <File className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "folder",
    label: "Folder",
    icon: <Folder className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "tag",
    label: "Tag",
    icon: <Tag className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "star",
    label: "Star",
    icon: <Star className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "pin",
    label: "Pin",
    icon: <Pin className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "note",
    label: "Note",
    icon: <StickyNote className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "image",
    label: "Image",
    icon: <Image className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "code",
    label: "Code",
    icon: <Code className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "book",
    label: "Book",
    icon: <Book className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "activity",
    label: "Activity",
    icon: <Activity className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "airplay",
    label: "Airplay",
    icon: <Airplay className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "alarm-clock",
    label: "Alarm Clock",
    icon: <AlarmClock className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "archive",
    label: "Archive",
    icon: <Archive className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "arrow-down",
    label: "Arrow Down",
    icon: <ArrowDown className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "arrow-left",
    label: "Arrow Left",
    icon: <ArrowLeft className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "arrow-right",
    label: "Arrow Right",
    icon: <ArrowRight className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "arrow-up",
    label: "Arrow Up",
    icon: <ArrowUp className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "bell",
    label: "Bell",
    icon: <Bell className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "bookmark",
    label: "Bookmark",
    icon: <Bookmark className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "briefcase",
    label: "Briefcase",
    icon: <Briefcase className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "calendar",
    label: "Calendar",
    icon: <Calendar className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "camera",
    label: "Camera",
    icon: <Camera className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "check",
    label: "Check",
    icon: <Check className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "chevron-down",
    label: "Chevron Down",
    icon: <ChevronDown className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "chevron-left",
    label: "Chevron Left",
    icon: <ChevronLeft className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "chevron-right",
    label: "Chevron Right",
    icon: <ChevronRight className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "chevron-up",
    label: "Chevron Up",
    icon: <ChevronUp className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "circle",
    label: "Circle",
    icon: <Circle className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "clock",
    label: "Clock",
    icon: <Clock className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "cloud",
    label: "Cloud",
    icon: <Cloud className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "code-2",
    label: "Code 2",
    icon: <Code2 className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "command",
    label: "Command",
    icon: <Command className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "compass",
    label: "Compass",
    icon: <Compass className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "copy",
    label: "Copy",
    icon: <Copy className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "credit-card",
    label: "Credit Card",
    icon: <CreditCard className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "crown",
    label: "Crown",
    icon: <Crown className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "database",
    label: "Database",
    icon: <Database className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "download",
    label: "Download",
    icon: <Download className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "edit",
    label: "Edit",
    icon: <Edit className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "external-link",
    label: "External Link",
    icon: <ExternalLink className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "eye",
    label: "Eye",
    icon: <Eye className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "flag",
    label: "Flag",
    icon: <Flag className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "gift",
    label: "Gift",
    icon: <Gift className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "globe",
    label: "Globe",
    icon: <Globe className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "heart",
    label: "Heart",
    icon: <Heart className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "home",
    label: "Home",
    icon: <Home className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "inbox",
    label: "Inbox",
    icon: <Inbox className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "key",
    label: "Key",
    icon: <Key className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "layout-grid",
    label: "Layout Grid",
    icon: <LayoutGrid className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "link",
    label: "Link",
    icon: <Link className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "lock",
    label: "Lock",
    icon: <Lock className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "mail",
    label: "Mail",
    icon: <Mail className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "map-pin",
    label: "Map Pin",
    icon: <MapPin className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "message-circle",
    label: "Message Circle",
    icon: <MessageCircle className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "mic",
    label: "Mic",
    icon: <Mic className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "moon",
    label: "Moon",
    icon: <Moon className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "music",
    label: "Music",
    icon: <Music className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "palette",
    label: "Palette",
    icon: <Palette className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "paperclip",
    label: "Paperclip",
    icon: <Paperclip className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "play",
    label: "Play",
    icon: <Play className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "plus",
    label: "Plus",
    icon: <Plus className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "search",
    label: "Search",
    icon: <Search className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "send",
    label: "Send",
    icon: <Send className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "settings",
    label: "Settings",
    icon: <Settings className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "shield",
    label: "Shield",
    icon: <Shield className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "shopping-cart",
    label: "Shopping Cart",
    icon: <ShoppingCart className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "smartphone",
    label: "Smartphone",
    icon: <Smartphone className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "speaker",
    label: "Speaker",
    icon: <Speaker className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "sun",
    label: "Sun",
    icon: <Sun className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "terminal",
    label: "Terminal",
    icon: <Terminal className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "trash",
    label: "Trash",
    icon: <Trash2 className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "upload",
    label: "Upload",
    icon: <Upload className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "user",
    label: "User",
    icon: <User className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "users",
    label: "Users",
    icon: <Users className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "video",
    label: "Video",
    icon: <Video className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "wand",
    label: "Wand",
    icon: <Wand2 className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "wifi",
    label: "Wifi",
    icon: <Wifi className="h-5 w-5" aria-hidden="true" />,
  },
  {
    id: "zap",
    label: "Zap",
    icon: <Zap className="h-5 w-5" aria-hidden="true" />,
  },
];

