import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { SnackbarProvider } from "../lib/components/Snackbar";
import { ThemeProvider } from "../lib/components/ThemeProvider";
import LayoutShell from "../lib/components/LayoutShell";
import SidebarMenu from "../lib/components/SidebarMenu";
import { Workflow, Settings, Key } from "lucide-react";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const iconClassName = "h-4 w-4";

const homeIcon = (
  <svg
    className={iconClassName}
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
  >
    <path d="M3 10.5 12 3l9 7.5" />
    <path d="M5 10v10h14V10" />
  </svg>
);

const docsIcon = (
  <svg
    className={iconClassName}
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
  >
    <path d="M7 3h8l4 4v14H7z" />
    <path d="M15 3v4h4" />
  </svg>
);

const databaseIcon = (
  <svg
    className={iconClassName}
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
  >
    <ellipse cx="12" cy="5" rx="8" ry="3" />
    <path d="M4 5v7c0 1.7 3.6 3 8 3s8-1.3 8-3V5" />
    <path d="M4 12v7c0 1.7 3.6 3 8 3s8-1.3 8-3v-7" />
  </svg>
);

export const workflowIcon = <Workflow className="h-4 w-4" />;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const menuItems = [
  {
    label: "Home",
    href: "/ui",
    description: "Overview and quick actions",
    icon: homeIcon,
  },
  {
    label: "Docs",
    href: "/ui/doc",
    description: "Markdown workspace",
    icon: docsIcon,
  },
  {
    label: "Database",
    href: "/ui/db",
    description: "Data tools and setup",
    icon: databaseIcon,
  },
  {
    label: "Workflow",
    href: "/ui/flow",
    description: "Flow tools and setup",
    icon: workflowIcon,
  },
  {
    label: "Settings",
    description: "App configuration",
    icon: <Settings className="h-4 w-4" />,
    submenu: [
      {
        label: "AI API Key",
        href: "/ui/settings/api-key",
        description: "Configure AI API credentials",
        icon: <Key className="h-4 w-4" />,
      },
    ],
  },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased duration-200`}
      >
        <ThemeProvider>
          <SnackbarProvider>
            <LayoutShell>
              <div className="flex h-full overflow-hidden">
                <SidebarMenu title="Navigation" items={menuItems} />
                {children}
                {/* <div className="flex-1 overflow-auto">{children}</div> */}
              </div>
            </LayoutShell>
          </SnackbarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
